apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test2
  name: test2
spec:
  containers:
  - command:
    - sh 
    - -c 
    - 'while [ 1 -eq 1 ]; do echo "Logs here" && sleep 3 ; done'
    image: busybox
    name: test2
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
