grafana:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
    labels: {}

    hosts:
      - grafana.cindrak.com
    path: /

alertmanager:
  ingress:
    enabled: true

    annotations:
      kubernetes.io/ingress.class: "nginx"

    labels: { }

    hosts:
      - alertmanager.cindrak.com

    paths:
      - /
