---
# tasks file for logstash
- name: Creating docker compose dir
  file:
    path: "/var/docker-compose-files"
    state: directory

- name: Check that the docker-compose.yml exists
  stat:
    path: /var/docker-compose-files/docker-compose.yml
  register: stat_result

- name: Making sure containers are down
  command:
    chdir: "/var/docker-compose-files"
    cmd: docker-compose down
  when: stat_result.stat.exists

- name: Copying custom dockerfile to build fluentd
  become: true
  copy:
      src: dockerfile
      dest: /var/docker-compose-files

- name: Building custom fluentd image
  command:
    chdir: "/var/docker-compose-files"
    cmd: docker build -t fluentd:v1 .


- name: Copying docker-compose directory
  become: true
  copy:
      src: docker-compose.yml
      dest: /var/docker-compose-files

- name: Creating config dirs
  file:
    path: "/etc/{{ item }}"
    state: directory
  loop: ["loki", "fluentd" , "fluentd" ,"minio"]

- name: Setting up fluentd config
  template:
    src: fluentd-conf.j2
    dest: /etc/fluentd/fluentd.conf

- name: Copying config file for Loki
  copy:
    src: loki-config.yaml
    dest: /etc/loki/config.yaml


- name: Running docker-compose on services to start
  command:
    chdir: "/var/docker-compose-files"
    cmd: docker-compose up -d