version: "3.19"
services:
  logstash:
    image: grafana/logstash-output-loki:main
      
    ports:
      - "9200:9200"
    command: logstash -f /etc/logstash/conf.d/kafka.conf
    volumes:
      - /etc/logstash/conf.d:/etc/logstash/conf.d
    environment:
      - MONITORING_ENABLED=false
      - XPACK_MONITORING_ENABLED=false
    networks:
      - logstash-network

  gafana:
    image: grafana/grafana:latest
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    depends_on:
      - loki
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
          - name: Loki
            type: loki
            access: proxy
            url: http://loki:3100
            jsonData:
              httpHeaderName1: "X-Scope-OrgID"
            secureJsonData:
              httpHeaderValue1: "tenant1"
        EOF
        /run.sh
    ports:
      - "3000:3000"
    networks:
      - logstash-network

  loki:
    image: grafana/loki:main
    ports:
        - "3100:3100"
        - "7946"
        - "9095"
    volumes:
        - /etc/loki:/etc/loki
    command: -config.file=/etc/loki/config.yaml
    networks:
      - logstash-network
    depends_on:
      - minio

  minio:
    image: minio/minio
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /data/loki-data && \
        mkdir -p /data/loki-ruler && \
        minio server /data
    environment:
      - MINIO_ACCESS_KEY=loki
      - MINIO_SECRET_KEY=supersecret
      - MINIO_PROMETHEUS_AUTH_TYPE=public
      - MINIO_UPDATE=off
    ports:
      - 9000
    volumes:
      - /etc/minio/data:/data
    networks:
      - logstash-network


networks:
  logstash-network:
    driver: bridge